-- TẠO STORE PROCEDURES BÁC SĨ 
CREATE PROC SP_THEMBACSI (@MABS CHAR (20) ,@HOBS NVARCHAR(30), @TENBS NVARCHAR (30) ,  @CHUCVU NVARCHAR (20) , @MaK CHAR (20))
AS
INSERT INTO BACSI VALUES (@MABS  ,@HOBS , @TENBS  ,  @CHUCVU  , @MaK)
GO 

--EXEC SP_THEMBACSI 'BS00011',N'NUYỄN CÔNG ',N'TOÀN',N'BÁC SĨ HẠNG 1' ,'KH0001'
GO 

SELECT*FROM BACSI 
GO 
-- XOÁ 
CREATE PROC SP_XOABACSI (@MABS CHAR (20))
AS 
DELETE BACSI WHERE MABS = @MABS 
GO 
--EXEC SP_XOABACSI 'BS00011'
GO

-- SỬA
CREATE PROC SP_SUABACSI(@MABS CHAR (20) ,@HOBS NVARCHAR(30), @TENBS NVARCHAR (30) ,  @CHUCVU NVARCHAR (20) , @MaK CHAR (20))
AS
 UPDATE BACSI 
 SET HOBS = @HOBS 
    ,TENBS = @TENBS 
	,CHUCVU = @CHUCVU 
	, MaK = @MaK
 WHERE MABS = @MABS
 GO 
 --EXEC SP_SUABACSI 'BS00011',N'LÊ CÔNG ',N'TRÍ',N'BÁC SĨ HẠNG 1' ,'KH0001'
GO

 -- TẠO STORE PROCEDURES BỆNH ÁN 
 CREATE  PROC SP_THEMBENHAN (@MABA CHAR (20)  ,@MABN CHAR (20), @KETQUA NVARCHAR (50))
 AS 
 INSERT INTO BENHAN VALUES (@MABA   ,@MABN , @KETQUA )
 GO 

 SELECT*FROM BENHAN 
 GO 
 --EXEC SP_THEMBENHAN'BA1011','BN00010',N'VIÊM THỰC QUẢN'
GO
	-- XOÁ 
CREATE PROC SP_XOABENHAN (@MABA CHAR (20))
AS 
DELETE BENHAN WHERE MABA = @MABA
GO 
--EXEC SP_XOABENHAN  'BA1011'
GO

-- SỬA 
CREATE PROC SP_SUABENHAN (@MABA CHAR (20)  ,@MABN CHAR (20), @KETQUA NVARCHAR (50))
AS
UPDATE BENHAN 
SET MABN = @MABN 
   ,KETQUA = @KETQUA 
WHERE MABA = @MABA 
GO 
--EXEC SP_SUABENHAN  'BA1011','BN00010',N'VIÊM THỰC QUẢN CẤP TÍNH'
GO 

 -- TẠO STORE PROCEDURES BỆNH NHÂN  
 CREATE  PROC SP_THEMBENHNHAN (@MABN CHAR (20), @HOBN NVARCHAR(30), @TENBN NVARCHAR (30), @SODTH VARCHAR(11), 
                               @DIACHI NVARCHAR(50), @NGAYSINH DATETIME , @PHAI NVARCHAR(10), @MAPHG CHAR (20))
 AS 
 INSERT INTO BENHNHAN VALUES (@MABN, @HOBN, @TENBN, @SODTH, @DIACHI, @NGAYSINH, @PHAI, @MAPHG )
 GO 

 SELECT * FROM BENHNHAN 
 GO 

 --EXEC SP_THEMBENHNHAN 'BN00011',N'LÊ NGỌC MINH',N'ĐẮC','0813994098',N'24 KỲ ĐÔNG ,Q3,TP.HCM','06/21/2005',N'NAM','PDT005'
 GO
	-- XOÁ 
CREATE PROC SP_XOABENHNHAN (@MABN CHAR (20))
AS 
DELETE BENHNHAN WHERE MABN = @MABN
GO 

--EXEC SP_XOABENHNHAN 'BN00011'
GO 
-- SỬA 
CREATE PROC SP_SUABENHNHAN (@MABN CHAR (20), @HOBN NVARCHAR(30), @TENBN NVARCHAR (30), @SODTH VARCHAR(11), 
                            @DIACHI NVARCHAR(50), @NGAYSINH DATETIME , @PHAI NVARCHAR(10), @MAPHG CHAR (20))
AS
UPDATE BENHNHAN
SET HOBN = @HOBN , 
    TENBN = @TENBN , 
	SODTH = @SODTH , 
	DIACHI = @DIACHI , 
	NGAYSINH = @NGAYSINH , 
	PHAI = @PHAI , 
	MAPHG = @MAPHG
WHERE MABN = @MABN 
GO 

--EXEC SP_SUABENHNHAN 'BN00011',N'LÊ MINH',N'ĐẮC','0813994099',N'24 KỲ ĐÔNG ,Q3,TP.HCM','02/21/2005',N'NAM','PDT005'
GO
 -- TẠO STORE PROCEDURES BẢO HIỂM Y TẾ 
 CREATE  PROC SP_THEMBHYT (@MABHYT CHAR (15), @MABN CHAR (20), @NGAYCAP DATE, @NGAYHETHAN DATE)
 AS 
 INSERT INTO BHYT VALUES (@MABHYT, @MABN, @NGAYCAP, @NGAYHETHAN )
 GO 

 --EXEC SP_THEMBHYT 'HS7030120228893','BN0004','2/04/2015','2/04/2020'
 GO
 SELECT * FROM BHYT 
 GO 
	-- XOÁ 
CREATE PROC SP_XOABHYT (@MABHYT CHAR (15))
AS 
DELETE BHYT WHERE MABHYT = @MABHYT
GO 
 --EXEC SP_XOABHYT 'HS7030120228893'
 GO
-- SỬA 
CREATE PROC SP_SUABHYT (@MABHYT CHAR (15), @MABN CHAR (20), @NGAYCAP DATE, @NGAYHETHAN DATE)
AS
UPDATE BHYT 
SET MABN = @MABN 
   ,NGAYCAP = @NGAYCAP
   , NGAYHETHAN = @NGAYHETHAN
WHERE MABHYT = @MABHYT 
GO 
 --EXEC SP_SUABHYT 'HS7030120228893','BN0004','2/12/2015','2/12/2020'
 GO
 -- TẠO STORE PROCEDURES DỊCH VỤ  
 CREATE  PROC SP_THEMDV (@MADV CHAR (20), @TENDV NVARCHAR (100), @GIA MONEY)
 AS 
 INSERT INTO DICHVU VALUES (@MADV   ,@TENDV , @GIA )
 GO 

 SELECT * FROM DICHVU 
 GO 
 --EXEC SP_THEMDV 'DV0019',N'Nội soi trực tràng ống mềm không sinh thiết','895,000'
 GO 
	-- XOÁ 
CREATE PROC SP_XOADV (@MADV CHAR (20))
AS 
DELETE DICHVU WHERE MADV = @MADV
GO 
 --EXEC SP_XOADV 'DV0019'
 GO 
-- SỬA 
CREATE PROC SP_SUADV (@MADV CHAR (20), @TENDV NVARCHAR (100), @GIA MONEY)
AS
UPDATE DICHVU 
SET TENDV = @TENDV
   ,GIA = @GIA 
WHERE MADV = @MADV
GO 
 --EXEC SP_SUADV 'DV0019',N'KHÁM TỔNG QUÁT','200,000'
 GO 

 -- TẠO STORE PROCEDURES ĐIỀU TRỊ 
 CREATE  PROC SP_THEMDIEUTRI (@MAK CHAR(20) ,@MABN CHAR (20))
 AS 
 INSERT INTO DIEUTRI VALUES (@MAK ,@MABN )
 GO 

 SELECT*FROM DIEUTRI
 GO 

 --EXEC SP_THEMDIEUTRI 'KH0005','BN0002'
 GO 
	-- XOÁ 
CREATE PROC SP_XOADIEUTRI (@MAK CHAR(20) ,@MABN CHAR (20))
AS 
DELETE DIEUTRI WHERE MAK = @MAK AND MABN = @MABN
GO 
 --EXEC SP_XOADIEUTRI 'KH0005','BN0002'
 GO 

-- SỬA 
--CREATE PROC SP_SUADIEUTRI (@MAK CHAR(20) ,@MABN CHAR (20))
--AS
--UPDATE DIEUTRI
--SET 
--WHERE  MAK = @MAK AND MABN = @MABN
--GO 

-- THUỴ NHIÊN 

---HOA DON
SELECT * FROM HOADON
GO
 --THEM HOA DON
CREATE PROC SP_THEMHOADON(@MAHD CHAR (20), @MADV CHAR (20), @MABN CHAR (20), @THUOC CHAR (13), @SL INT, @THANHTIEN MONEY  )
AS 
INSERT INTO HOADON VALUES (@MAHD ,@MADV,@MABN ,@THUOC,@SL ,@THANHTIEN  )
GO 
EXEC SP_THEMHOADON 'HD00023', 'DV001', 'BN0003','TH0021','14','204,200'
GO

--SUA HOA DON
CREATE PROC SP_SUAHOADON (@MAHD CHAR (20)  , @MADV CHAR (20) ,@MABN CHAR (20)  , @THUOC CHAR (13), @SL INT, @THANHTIEN MONEY)
AS
UPDATE HOADON
SET
MADV =@MADV,
SL=@SL,
THANHTIEN = @THANHTIEN ,
THUOC=@THUOC,
MABN=@MABN
WHERE MAHD=@MAHD
GO
--EXEC SP_SUAHOADON 'HD00023', 'DV001', 'BN00010', NULL, NULL, '3,500,000'
GO
--XOA HOA DON
CREATE PROC SP_XOAHOADON (@MAHD CHAR (20) )
AS
DELETE HOADON
WHERE MAHD =@MAHD 
GO
--EXEC SP_XOAHOADON 'HD00023'
GO
--KHAM BENH
SELECT*FROM KHAM_BENH 
GO 

CREATE PROC SP_THEMKHAMBENH (@MABS CHAR(20),@MABN CHAR (20), @NGAYKHAM DATE )
AS 
INSERT INTO KHAM_BENH VALUES (@MABS ,@MABN , @NGAYKHAM  )
GO
--EXEC SP_THEMKHAMBENH  'BS0001','BN00010','12/4/2023'
GO
--SUA KHAM BENH
CREATE PROC SP_SUAKHAMBENH (@MABS CHAR(20),@MABN CHAR (20), @NGAYKHAM DATE )
AS
UPDATE KHAM_BENH
SET NGAYKHAM=@NGAYKHAM
WHERE MABS=@MABS AND MABN = @MABN
GO
--EXEC SP_SUAKHAMBENH 'BS0001','BN00010','12/25/2023'
GO
--XOA KHAM BENH
CREATE PROC SP_XOAKHAMBENH (@MABS CHAR(20),@MABN CHAR (20))
AS
DELETE KHAM_BENH 
WHERE MABS=@MABS AND MABN=@MABN
GO
--EXEC SP_XOAKHAMBENH 'BS0001','BN00010'
GO
--THEM KHOA
SELECT*FROM KHOA
GO 
CREATE PROC SP_THEMKHOA (@MAK CHAR(20)  , @TENK NVARCHAR (30) )
AS
INSERT INTO KHOA VALUES (@MAK , @TENK)
GO
--EXEC SP_THEMKHOA 'KH0006',N'KHOA NHI'
GO
--SUA KHOA
CREATE PROC SP_SUAKHOA (@MAK CHAR(20)  , @TENK NVARCHAR (30) )
AS
UPDATE KHOA
SET TENK =@TENK
WHERE MAK=@MAK
GO
--EXEC SP_SUAKHOA 'KH0006',N'KHOA THẦN KINH'
GO
--XOA KHOA
CREATE PROC SP_XOAKHOA (@MAK CHAR(20)   )
AS
DELETE KHOA 
WHERE MAK=@MAK
GO
--EXEC SP_XOAKHOA  'KH0006'
GO
--THEM KHOA_NV
SELECT*FROM KHOA_NV
GO 
CREATE PROC SP_THEMKHOA_NV (@MAK CHAR(20) ,@MANV CHAR (20))
AS 
INSERT INTO KHOA_NV VALUES (@MAK,@MANV)
GO
--EXEC SP_THEMKHOA_NV 'KH0005','NV00010'
GO
--SUA KHOA_NV
--CREATE PROC SP_SUAKHOA_NV (@MAK CHAR(20) ,@MANV CHAR (20))
--AS
--UPDATE KHOA_NV
--SET MANV=@MANV
--WHERE MAK=@MAK
--GO
--EXEC SP_SUAKHOA_NV 'KH0006','NV00011'
--GO
--XOA KHOA_NV
CREATE PROC SP_XOAKHOA_NV(@MAK CHAR(20) ,@MANV CHAR (20))
AS
DELETE KHOA_NV 
WHERE MAK=@MAK AND MANV=@MANV
GO
--EXEC SP_XOAKHOA_NV 'KH0005','NV00010' 
GO

SELECT *FROM LICHSU_BA
GO 
--THEM LICH SU BENH AN
CREATE PROC SP_THEMLICHSU_BA (@MABS CHAR(20) ,@MABA CHAR (20), @NGAYVIET DATE )
AS
INSERT INTO LICHSU_BA VALUES (@MABS  ,@MABA , @NGAYVIET  )
GO 
--EXEC SP_THEMLICHSU_BA  'BS0001','BA109','12/4/2023'
GO
--SUA LICH SU BENH AN
CREATE PROC SP_SUALICHSU_BA (@MABS CHAR(20) ,@MABA CHAR (20), @NGAYVIET DATE )
AS
UPDATE LICHSU_BA 
SET 
NGAYVIET=@NGAYVIET
WHERE MABS=@MABS AND MABA=@MABA
GO
--EXEC SP_SUALICHSU_BA 'BS0001','BA109','1/4/2023'
GO
--XOA LICH SU BENH AN
CREATE PROC SP_XOALICHSU_BA (@MABS CHAR(20) ,@MABA CHAR (20) )
AS
DELETE LICHSU_BA 
WHERE MABS=@MABS AND MABA=@MABA
GO
--EXEC SP_XOALICHSU_BA 'BS0001','BA109'
GO
--THEM MUA THUOC 
SELECT * FROM MUA_THUOC 
GO 
CREATE PROC SP_THEMMAUTHUOC (@MATHUOC CHAR(13), @MABN CHAR (20) , @SL INT)
AS
INSERT INTO MUA_THUOC VALUES (@MATHUOC  ,@MABN  , @SL)
GO
--EXEC SP_THEMMAUTHUOC 'TH0025','BN00010','14'
GO
--SUA MUA THUOC 
CREATE PROC SP_SUAMUATHUOC (@MATHUOC CHAR(13), @MABN CHAR (20) , @SL INT)
AS
UPDATE MUA_THUOC 
SET 
SL=@SL
WHERE MATHUOC = @MATHUOC AND MABN=@MABN 
GO
--EXEC SP_SUAMUATHUOC  'TH0025','BN00010','1'
GO
--XOA MUA THUOC 
CREATE PROC SP_XOAMUATHUOC (@MATHUOC CHAR(13), @MABN CHAR (20) )
AS
DELETE MUA_THUOC 
WHERE MATHUOC=@MATHUOC AND MABN=@MABN
GO
--EXEC SP_XOAMUATHUOC 'TH0025','BN00010'
GO