--------UPDATE CHO BAC SI-----------------------------
UPDATE BACSI 
SET CHUCVU =N'BÁC SĨ HẠNG 3 '
WHERE MABS ='BS0002 ' 
GO

UPDATE BACSI
SET CHUCVU = N'BÁC SĨ HẠNG 1'
WHERE MABS = 'BS0008'
 GO

 UPDATE BACSI
 SET CHUCVU = N'BÁC SĨ HẠNG 2 '
 WHERE MABS ='BS0007 '
 GO

 SELECT*FROM BACSI 
 GO
  ----------UPDATE CHO BHYT----------------------------------------------
  UPDATE BHYT
  SET NGAYCAP ='3-04-2020' 
  WHERE MABHYT ='HS7030120228897 '
  GO

  UPDATE BHYT
  SET NGAYHETHAN = '3-04-2025'
  WHERE MABHYT = 'HS7030120228897'
 GO
 SELECT*FROM BHYT
 GO