-- Tạo các stored procedures 
-- TÌM BÁC SĨ BẰNG TÊN 
CREATE PROC SP_TIMBACSI_BANGTEN (@TEN NVARCHAR(30))
AS 
SELECT * FROM BACSI WHERE TENBS LIKE N'%'+@TEN+'%'
GO 

--EXEC SP_TIMBACSI_BANGTEN 'NGÂN'
go 
 -- TÌM BỆNH ÁN BẰNG TÊN BỆNH NHÂN 
 CREATE PROC SP_TIMBENHAN_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT BENHAN.MABA, BENHAN.MABN , BENHAN.KETQUA FROM BENHAN , BENHNHAN WHERE BENHAN.MABN = BENHNHAN.MABN AND (TENBN LIKE N'%'+@TEN+'%'OR  BENHNHAN.TENBN = @TEN)
 GO 

 --EXEC SP_TIMBENHAN_BANGTENBN 'THUỶ'
go 
-- tìm bệnh nhân bằng tên 
 CREATE PROC SP_TIMBENHNHAN_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *FROM  BENHNHAN WHERE (TENBN LIKE N'%'+@TEN+'%'OR  BENHNHAN.TENBN = @TEN)
 GO 

 --EXEC SP_TIMBENHNHAN_BANGTEN'TÙNG'
 GO 
 -- TÌM BẢO HIỂM Y TẾ BẰNG TÊN BỆNH NHÂN 
 CREATE PROC SP_TIMBHYT_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT BHYT.MABHYT, BHYT.MABN , BHYT.NGAYCAP , BHYT.NGAYHETHAN FROM  BHYT ,BENHNHAN WHERE BHYT.MABN = BENHNHAN.MABN AND ( TENBN LIKE N'%'+@TEN+'%'OR  BENHNHAN.TENBN =  @TEN)
 GO 

--EXEC SP_TIMBHYT_BANGTENBN 'TÙNG'
 GO 

 -- TÌM DỊCH VỤ BẰNG TÊN 
 CREATE PROC SP_TIMDICHVU_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *FROM  DICHVU WHERE( DICHVU.TENDV LIKE N'%'+@TEN+'%' OR  TENDV =  @TEN)
 GO 

 --EXEC SP_TIMDICHVU_BANGTEN 'TH'
 GO 
 -- TÌM ĐIỀU TRỊ BẰNG TÊN BỆNH NHÂN 
 CREATE PROC SP_TIMDIEUTRI_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT DIEUTRI.MABN , DIEUTRI.MAK FROM DIEUTRI, BENHNHAN WHERE DIEUTRI.MABN = BENHNHAN.MABN AND ( TENBN LIKE N'%'+@TEN+'%' OR  BENHNHAN.TENBN =  @TEN)
 GO 

 --EXEC SP_TIMDIEUTRIBANGTENBN 'THUY'
 GO 
 -- tìm hoá đơn bằng tên bệnh nhân 
 CREATE PROC SP_TIMHOADON_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT HOADON.MAHD , HOADON.MADV , HOADON.MABN , HOADON.THUOC , HOADON.SL ,HOADON.THANHTIEN FROM HOADON , BENHNHAN WHERE HOADON.MABN = BENHNHAN.MABN AND (BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR  BENHNHAN.TENBN =  @TEN)
 GO 

-- EXEC SP_TIMHOADON_BANGTENBN'TÙNG'
 GO 
 
 -- TÌM KIẾM KHÁM BỆNH BẰNG TÊN BỆNH NHÂN 
 CREATE PROC SP_TIMKHAMBENH_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT KHAM_BENH.MABS , KHAM_BENH.MABN , KHAM_BENH.NGAYKHAM  
 FROM KHAM_BENH , BENHNHAN 
 WHERE KHAM_BENH.MABN = BENHNHAN.MABN AND (BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR  BENHNHAN.TENBN =  @TEN) 
 GO 
 --EXEC SP_TIMKHAMBENH_BANGTENBN'TÙNG'
 GO 
 -- TÌM KIẾM KHOA BẰNG TÊN KHOA 
  CREATE PROC SP_TIMKHOA_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT * 
 FROM KHOA 
 WHERE (TENK LIKE N'%'+@TEN+'%' OR  TENK =  @TEN) 
 GO 
 --EXEC SP_TIMKHOA_BANGTEN N'KH'
 GO 
 -- TÌM KHIẾM KHOA NHÂN VIÊN BẰNG TÊN NHÂN VIÊN 
  CREATE PROC SP_TIMKHOA_NV_BANGTENNV(@TEN NVARCHAR(30))
 AS
 SELECT KHOA_NV.MAK , KHOA_NV.MANV
 FROM KHOA_NV , NHANVIEN
 WHERE KHOA_NV.MANV = NHANVIEN.MANV AND (NHANVIEN.TENNV LIKE N'%'+@TEN+'%' OR  NHANVIEN.TENNV =  @TEN) 
 GO 
 --EXEC SP_TIMKHOA_NV_BANGTENNV'ANH'
 GO 

 -- TÌM KIẾM LỊCH SỬ BỆNH ÁN BẰNG TÊN BỆNH NHÂN 
  CREATE PROC SP_TIMLICHSUBA_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT LICHSU_BA.MABS , LICHSU_BA.MABA, LICHSU_BA.NGAYVIET
 FROM LICHSU_BA, BENHNHAN , BENHAN 
 WHERE  BENHAN.MABN = BENHNHAN.MABN AND BENHAN.MABA = LICHSU_BA.MABA AND ( TENBN LIKE N'%'+@TEN+'%' OR  BENHNHAN.TENBN = @TEN)
 GO 
 --EXEC SP_TIMLICHSUBA_BANGTENBN N'THUỶ'
 GO 

 -- TÌM KIẾM MUA THUỐC BẰNG TÊN THUỐC  
  CREATE PROC SP_TIMMUA_THUOC_BANGTENTHUOC(@TEN NVARCHAR(30))
 AS
 SELECT MUA_THUOC.MATHUOC , MUA_THUOC.MABN , MUA_THUOC.SL
 FROM MUA_THUOC, THUOC
 WHERE  MUA_THUOC.MATHUOC = THUOC.MATHUOC AND ( THUOC.TENTHUOC LIKE N'%'+@TEN+'%' OR  THUOC.TENTHUOC = @TEN)
 GO 
 --EXEC SP_TIMMUA_THUOC_BANGTENTHUOC N'Thuốc Tocemux điều trị tiêu chất nhầy, bệnh lý hô hấp có đờm'
 GO 
   CREATE PROC SP_TIMNHANVIEN_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM NHANVIEN
 WHERE ( TENNV LIKE N'%'+@TEN+'%' OR  TENNV = @TEN)
 GO 
 --EXEC SP_TIMNHANVIEN_BANGTEN N'Trung'
 GO 
 -- TÌM KIẾM PHÒNG ĐIỀU TRỊ BẰNG LOẠI PHÒNG 

 CREATE PROC SP_TIMPHONGDIEUTRI_BANGLOAIPHG(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM PHONGDIEUTRI
 WHERE ( LOAIPHONG LIKE N'%'+@TEN+'%' OR  LOAIPHONG = @TEN)
 GO 
 --EXEC SP_TIMPHONGDIEUTRI_BANGLOAIPHG N'ĐÔI'
 GO 
 -- TÌM KIẾM PHÒNG KHÁM BẰNG TÊN KHOA 
 CREATE PROC SP_TIMPHONGKHAM_BANGTENKHOA(@TEN NVARCHAR(30))
 AS
 SELECT PHONGKHAM.MAPK , PHONGKHAM.MAK 
 FROM PHONGKHAM , KHOA
 WHERE KHOA.MAK = PHONGKHAM.MAK AND ( KHOA.TENK LIKE N'%'+@TEN+'%' OR KHOA.TENK  = @TEN)
 GO 
 --EXEC SP_TIMPHONGKHAM_BANGTENKHOA N'KHOA NỘI'
 GO

 --TÌM KIẾM PHÒNG KHÁM _ BỆNH NHÂN BẰNG TÊN BỆNH NHÂN 
  CREATE PROC SP_TIMPKHAM_BENHNHAN_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT PKHAM_BENHNHAN.MAPK , PKHAM_BENHNHAN.MABN , PKHAM_BENHNHAN.TGIAN
 FROM PKHAM_BENHNHAN , BENHNHAN
 WHERE PKHAM_BENHNHAN.MABN = BENHNHAN.MABN AND ( BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR BENHNHAN.TENBN  = @TEN)
 GO 
 --EXEC SP_TIMPKHAM_BENHNHAN_BANGTENBN N'TÙNG'
 GO 

-- TÌM KIẾM SỬ DỤNG DỊCH VỤ BẰNG TÊN BỆNH NHÂN 
  CREATE PROC SP_TIMSUDUNG_DICHVU_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT SUDUNG_DICHVU.MADV, SUDUNG_DICHVU.MABN , SUDUNG_DICHVU.TGIAN , SUDUNG_DICHVU.SL
 FROM SUDUNG_DICHVU , BENHNHAN
 WHERE SUDUNG_DICHVU.MABN = BENHNHAN.MABN AND ( BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR BENHNHAN.TENBN  = @TEN)
 GO 
 --EXEC SP_TIMSUDUNG_DICHVU_BANGTENBN N'TÙNG'
 GO 
 -- TÌM KIẾM THỐC BẴNG TÊN THUỐC 
   CREATE PROC SP_TIMTHUOC_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM THUOC
 WHERE ( TENTHUOC LIKE N'%'+@TEN+'%' OR TENTHUOC  = @TEN)
 GO 
 --EXEC SP_TIMTHUOC_BANGTEN N'Thuốc nhỏ mắt'
 GO