-- XUẤT DANH SÁCH BÁC SĨ 
CREATE PROC SP_XUATBACSI 
AS
SELECT * FROM BACSI 
GO 
EXEC SP_XUATBACSI
GO 

-- XUẤT DANH SÁCH BỆNH ÁN 
CREATE PROC SP_XUATBENHAN 
AS
SELECT * FROM BENHAN
GO 
EXEC SP_XUATBENHAN
GO 

-- XUẤT DANH SÁCH BỆNH NHÂN
CREATE PROC SP_XUATBENHNHAN
AS
SELECT * FROM BENHNHAN 
GO 
EXEC SP_XUATBENHNHAN
GO 

-- XUẤT DANH SÁCH BHYT
CREATE PROC SP_XUATBHYT
AS
SELECT * FROM BHYT
GO 
EXEC SP_XUATBHYT
GO 

-- XUẤT DANH SÁCH DỊCH VỤ 
CREATE PROC SP_XUATDICHVU 
AS
SELECT * FROM DICHVU 
GO 
EXEC SP_XUATDICHVU 
GO 

-- XUẤT DANH SÁCH ĐIỀU TRỊ
CREATE PROC SP_XUATDIEUTRI 
AS
SELECT * FROM DIEUTRI
GO 
EXEC SP_XUATDIEUTRI
GO 

-- XUẤT DANH SÁCH HOÁ ĐƠN
CREATE PROC SP_XUATHOADON 
AS
SELECT * FROM HOADON 
GO 
EXEC SP_XUATHOADON
GO 

-- XUẤT DANH SÁCH KHÁM BỆNH
CREATE PROC SP_XUATKHAM_BENH
AS
SELECT * FROM KHAM_BENH 
GO 
EXEC SP_XUATKHAM_BENH
GO 

-- XUẤT DANH SÁCH KHOA
CREATE PROC SP_XUATKHOA
AS
SELECT * FROM KHOA 
GO 
EXEC SP_XUATKHOA
GO 

-- XUẤT DANH SÁCH KHOA NHÂN VIÊN 
CREATE PROC SP_XUATKHOA_NV
AS
SELECT * FROM KHOA_NV
GO 
EXEC SP_XUATKHOA_NV
GO 

-- XUẤT DANH SÁCH LỊCH SỬ BỆNH ÁN 
CREATE PROC SP_XUATLICHSU_BA
AS
SELECT * FROM LICHSU_BA
GO 
EXEC SP_XUATLICHSU_BA
GO 

-- XUẤT DANH SÁCH MUA THUỐC
CREATE PROC SP_XUATMUATHUOC
AS
SELECT * FROM MUA_THUOC 
GO 
EXEC SP_XUATMUATHUOC
GO 

-- XUẤT DANH SÁCH NHÂN VIÊN 
CREATE PROC SP_XUATNHANVIEN
AS
SELECT * FROM NHANVIEN
GO 
EXEC SP_XUATNHANVIEN
GO 

-- XUẤT DANH SÁCH PHONG ĐIỀU TRỊ 
CREATE PROC SP_XUATPHONGDIEUTRI
AS
SELECT * FROM PHONGDIEUTRI 
GO 
EXEC SP_XUATPHONGDIEUTRI
GO 

-- XUẤT DANH SÁCH PHÒNG KHÁM 
CREATE PROC SP_XUATPHONGKHAM
AS
SELECT * FROM PHONGKHAM 
GO 
EXEC SP_XUATPHONGKHAM
GO 

-- XUẤT DANH SÁCH PHÒNG KHÁM BỆNH NHÂN
CREATE PROC SP_XUATPKHAM_BENHNHAN
AS
SELECT * FROM PKHAM_BENHNHAN
GO 
EXEC SP_XUATPKHAM_BENHNHAN
GO 

-- XUẤT DANH SÁCH SỬ DỤNG DỊCH VỤ 
CREATE PROC SP_XUATSUDUNG_DICHVU
AS
SELECT * FROM SUDUNG_DICHVU 
GO 
EXEC SP_XUATSUDUNG_DICHVU
GO 

-- XUẤT DANH SÁCH THUỐC 
CREATE PROC SP_XUATTHUOC
AS
SELECT * FROM THUOC 
GO 
EXEC SP_XUATTHUOC
GO 